### ISSUE TITLE
Use "attrib", not "atrib"

### ISSUE THREAD

**Issue by cmarqu** [amiq-consulting/amiq_rm#1]
I would say the generally used abbreviation for "attribute" in code is ``attrib`` - is your use of ``atrib`` just a typo maybe?

**Comment by amiq-consulting** [comment]
Hi! Thanks for pointing this out. We have fixed the typo. If you have any other feedback feel free to share it with us!

Best regards,
Amiq

**Comment by cmarqu** [comment]
Thanks for the quick fix.
Do you still have the ``Doxyfile`` around (it's not in the repo) - then you (or the users themselves) could build the documentation, which still refers to ``atrib`` right now.

**Comment by amiq-consulting** [comment]
The Documentation will be updated next week.

**Comment by amiq-consulting** [comment]
Hi! We have regenerated the documentation and added the Doxyfile as well.

Regards,
Amiq
